app_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('base.urls', 'base'), namespace="base")),
    path('inv/', include(('inv.urls', 'inv'), namespace="inv")),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace="cmp")),
    path('admin/', admin.site.urls),
]

cmp/urls.py
from django.urls import path
from cmp.views import (
    ProveedorView, ProveedorNew, ProveedorEdit, proveedor_inactivar
)

urlpatterns = [
    path('proveedor/', ProveedorView.as_view(), name="proveedor_list"),
    path('proveedor/new/', ProveedorNew.as_view(), name="proveedor_new"),
    path('proveedor/edit/<int:pk>', ProveedorEdit.as_view(), name="proveedor_edit"),

    path('proveedor/inactivar/<int:id>', proveedor_inactivar, name="proveedor_inactivar")
    
]

inv/urls.py
from django.urls import path
from inv.views import (
    CategiaView, CategoriaNew, CategoriaEdit, CategoriaDel, SubCategiaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel,
    MarcaView, MarcaNew, MarcaEdit, marca_inactiva, UnidadMedidaView, UnidadMedidaNew, UnidadMedidaEdit, unidadmedida_inactiva,
    ProductoView, ProductoNew ,ProductoEdit, producto_inactiva
)

urlpatterns = [
    path('categorias/', CategiaView.as_view(), name="categoria_list"),
    path('categorias/new/', CategoriaNew.as_view(), name="categoria_new"),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name="categoria_edit"), 
    path('categorias/del/<int:pk>', CategoriaDel.as_view(), name="categoria_del"),

    path('subcategorias/', SubCategiaView.as_view(), name="subcategoria_list"),
    path('subcategorias/new/', SubCategoriaNew.as_view(), name="subcategoria_new"),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name="subcategoria_edit"),
    path('subcategorias/del/<int:pk>', SubCategoriaDel.as_view(), name="subcategoria_del"),

    path('marca/', MarcaView.as_view(), name="marca_list"),
    path('marca/new/', MarcaNew.as_view(), name="marca_new"),
    path('marca/edit/<int:pk>', MarcaEdit.as_view(), name="marca_edit"),
    path('marca/del/<int:id>', marca_inactiva, name="marca_inactivar"),

    path('unidadmedida/', UnidadMedidaView.as_view(), name="unidadmedida_list"),
    path('unidadmedida/new/', UnidadMedidaNew.as_view(), name="unidadmedida_new"),
    path('unidadmedida/edit/<int:pk>', UnidadMedidaEdit.as_view(), name="unidadmedida_edit"),
    path('unidadmedida/del/<int:id>', unidadmedida_inactiva, name="unidadmedida_inactivar"),

    path('producto/', ProductoView.as_view(), name="producto_list"),
    path('producto/new/', ProductoNew.as_view(), name="producto_new"),
    path('producto/edit/<int:pk>', ProductoEdit.as_view(), name="producto_edit"),
    path('producto/del/<int:id>', producto_inactiva, name="producto_inactivar")


]

base/models.py
from django.db import models
from django.contrib.auth.models import User


class ModelBase(models.Model):
    '''
    auto_now_add = agrega fecha y hora solo en creacion
    auto_now = cada vez que cambie algo cambia la fecha
    '''
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True, null=True)

    class Meta:
        ''' No toma encuenta el modelo al crear migraciones'''
        abstract = True

inv/models.py
from django.db import models


from base.models import ModelBase

class Categoria(ModelBase):
    descripcion = models.CharField(max_length=100, help_text='Descripción de la categoria', unique=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super().save()

    class Meta:
        verbose_name_plural = 'Categorias'


class SubCategoria(ModelBase):
    categoria =  models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=100, help_text='Descripción de la categoria')

    def __str__(self):
        return '{}: {}'.format(self.categoria.descripcion, self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super().save()

    class Meta:
        verbose_name_plural = 'Sub Categorias'
        unique_together = ('categoria', 'descripcion')

class Marca(ModelBase):
    descripcion = models.CharField(max_length=100, help_text='Descripción de la marca')

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super().save()

    class Meta:
        verbose_name_plural = 'Marca'        


class UnidadMedida(ModelBase):
    descripcion = models.CharField(max_length=100, help_text='Unidad de medida')

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super().save()

    class Meta:
        verbose_name_plural = 'Unidades de medida'    

class Producto(ModelBase):
    codigo = models.CharField(max_length=20, unique=True)
    codigo_barras = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)

    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadMedida, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super().save()

    class Meta:
        verbose_name_plural = 'Productos'    
        unique_together = ('codigo', 'codigo_barras')
        

inv/forms.py
from django import forms

from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto


class FormBase(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })        

class CategoriaForm(FormBase):

    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {
            'descripcion':'Descripción de la categoria',
            'estado':"Estado"
        }
        widget = {
            'descripcion': forms.TextInput()
        }

class SubCategoriaForm(FormBase):
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.filter(estado=True).order_by('descripcion')
    )

    class Meta:
        model = SubCategoria
        fields = ['categoria', 'descripcion', 'estado']
        labels = {
            'descripcion':'Sub Categoria',
            'estado':"Estado"
        }
        widget = {
            'descripcion': forms.TextInput()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['categoria'].empty_label = 'Seleccione categoría'

class MarcaForm(FormBase):
    
    class Meta:
        model = Marca
        fields = ['descripcion', 'estado']
        labels = {
            'descripcion':'Marca',
            'estado':"Estado"
        }
        widget = {
            'descripcion': forms.TextInput()
        }
        
class UnidadMedidaForm(FormBase):
    
    class Meta:
        model = UnidadMedida
        fields = ['descripcion', 'estado']
        labels = {
            'descripcion':'Unidad de medida',
            'estado':"Estado"
        }
        widget = {
            'descripcion': forms.TextInput()
        }
    
class ProductoForm(FormBase):
    
    class Meta:
        model = Producto
        fields = [
            'codigo','codigo_barras','descripcion', 'estado', 'precio',
            'existencia', 'ultima_compra', 'marca', 'subcategoria',
            'unidad_medida'
        ]
        exclude = [
            'um', 'fm', 'uc', 'fc'
        ]
        widget = {
            'descripcion': forms.TextInput()
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ultima_compra'].widget.attrs['readonly'] = True
        self.fields['existencia'].widget.attrs['readonly'] = True

inv/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.messages.views import SuccessMessageMixin

from django.views import generic
from django.urls import reverse_lazy
from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto
from .forms import CategoriaForm, SubCategoriaForm, MarcaForm, UnidadMedidaForm, ProductoForm
from base.views import SinPrivilegios
# Create your views here.





class CategiaView(SinPrivilegios, generic.ListView):
    permission_required = 'inv.view_categoria'
    model = Categoria
    template_name = 'inv/categoria_list.html'    

class CategoriaNew(SinPrivilegios, SuccessMessageMixin, generic.CreateView):
    permission_required = 'inv.add_categoria'
    model = Categoria
    template_name = 'inv/categoria_form.html'    
    form_class = CategoriaForm
    success_url = reverse_lazy('inv:categoria_list')
    success_message = 'Categoria creada satisfatoriamente'

    def form_valid(self, form):
        form.instance.uc = self.request.user        
        return super().form_valid(form)

class CategoriaEdit(SinPrivilegios, SuccessMessageMixin, generic.UpdateView):
    permission_required = 'inv.change_categoria'
    model = Categoria
    template_name = 'inv/categoria_form.html'    
    form_class = CategoriaForm
    success_url = reverse_lazy('inv:categoria_list')
    success_message = 'Categoria actualizada satisfatoriamente'

    def form_valid(self, form):
        form.instance.um = self.request.user.id       
        return super().form_valid(form)

class CategoriaDel(SinPrivilegios, generic.DeleteView):
    permission_required = 'inv.delete_categoria'
    model = Categoria
    template_name = 'inv/catalogos_del.html'    
    success_url = reverse_lazy('inv:categoria_list')


class SubCategiaView(SinPrivilegios, generic.ListView):
    permission_required = 'inv.view_subcategoria'
    model = SubCategoria
    template_name = 'inv/subcategoria_list.html'    

class SubCategoriaNew(SinPrivilegios, generic.CreateView):
    permission_required = 'inv.add_subcategoria'
    model = SubCategoria
    template_name = 'inv/subcategoria_form.html'    
    form_class = SubCategoriaForm
    success_url = reverse_lazy('inv:subcategoria_list')

    def form_valid(self, form):
        form.instance.uc = self.request.user        
        return super().form_valid(form)

class SubCategoriaEdit(SinPrivilegios, generic.UpdateView):
    permission_required = 'inv.change_subcategoria'
    model = SubCategoria
    template_name = 'inv/subcategoria_form.html'    
    form_class = SubCategoriaForm
    success_url = reverse_lazy('inv:subcategoria_list')

    def form_valid(self, form):
        form.instance.um = self.request.user.id       
        return super().form_valid(form)

class SubCategoriaDel(SinPrivilegios, generic.DeleteView):
    permission_required = 'inv.delete_subcategoria'
    model = SubCategoria
    template_name = 'inv/catalogos_del.html'    
    success_url = reverse_lazy('inv:subcategoria_list')



class MarcaView(SinPrivilegios, generic.ListView):    
    permission_required = 'inv.view_marca'
    model = Marca
    template_name = 'inv/marca_list.html'    

class MarcaNew(SinPrivilegios, generic.CreateView):
    permission_required = 'inv.add_marca'
    model = Marca
    template_name = 'inv/marca_form.html'    
    form_class = MarcaForm
    success_url = reverse_lazy('inv:marca_list')

    def form_valid(self, form):
        form.instance.uc = self.request.user        
        return super().form_valid(form)

class MarcaEdit(SinPrivilegios, generic.UpdateView):
    permission_required = 'inv.change_marca'
    model = Marca
    template_name = 'inv/marca_form.html'    
    form_class = MarcaForm
    success_url = reverse_lazy('inv:marca_list')

    def form_valid(self, form):
        form.instance.um = self.request.user.id       
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.delete_marca', login_url='base:sinprivilegios')
def marca_inactiva(request, id):
    marca = Marca.objects.get(pk=id)
    context = {}
    template_name='inv/catalogos_del.html'

    if not marca:
        return redirect('inv:marca_list')
    
    if request.method == 'GET':
        context = {'obj': marca}

    if request.method == 'POST':
        marca.estado = False
        marca.save()
        messages.success(request, 'Marca inactivada')
        return redirect('inv:marca_list')

    return render(request, template_name, context)

class UnidadMedidaView(SinPrivilegios, generic.ListView):
    permission_required = 'inv.view_unidadmedida'
    model = UnidadMedida
    template_name = 'inv/unidadmedida_list.html'    

class UnidadMedidaNew(SinPrivilegios, generic.CreateView):
    permission_required = 'inv.add_unidadmedida'
    model = UnidadMedida
    template_name = 'inv/unidadmedida_form.html'    
    form_class = UnidadMedidaForm
    success_url = reverse_lazy('inv:unidadmedida_list')

    def form_valid(self, form):
        form.instance.uc = self.request.user        
        return super().form_valid(form)

class UnidadMedidaEdit(SinPrivilegios, generic.UpdateView):
    permission_required = 'inv.change_unidadmedida'
    model = UnidadMedida
    template_name = 'inv/unidadmedida_form.html'    
    form_class = UnidadMedidaForm
    success_url = reverse_lazy('inv:unidadmedida_list')

    def form_valid(self, form):
        form.instance.um = self.request.user.id       
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.delete_unidadmedida', login_url='base:sinprivilegios')
def unidadmedida_inactiva(request, id):
    unidadmedida = UnidadMedida.objects.get(pk=id)
    context = {}
    template_name='inv/catalogos_del.html'

    if not unidadmedida:
        return redirect('inv:unidadmedida_list')
    
    if request.method == 'GET':
        context = {'obj': marca}

    if request.method == 'POST':
        unidadmedida.estado = False
        unidadmedida.save()
        return redirect('inv:unidadmedida_list')

    return render(request, template_name, context)

class ProductoView(SinPrivilegios, generic.ListView):
    permission_required = 'inv.view_producto'
    model = Producto
    template_name = 'inv/producto_list.html'    

class ProductoNew(SinPrivilegios, generic.CreateView):
    permission_required = 'inv.add_producto'
    model = Producto
    template_name = 'inv/producto_form.html'    
    form_class = ProductoForm
    success_url = reverse_lazy('inv:producto_list')

    def form_valid(self, form):
        form.instance.uc = self.request.user        
        return super().form_valid(form)

class ProductoEdit(SinPrivilegios, generic.UpdateView):
    permission_required = 'inv.change_producto'
    model = Producto
    template_name = 'inv/producto_form.html'    
    form_class = ProductoForm
    success_url = reverse_lazy('inv:producto_list')

    def form_valid(self, form):
        form.instance.um = self.request.user.id       
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.delete_producto', login_url='base:sinprivilegios')
def producto_inactiva(request, id):
    producto = Producto.objects.get(pk=id)
    context = {}
    template_name='inv/catalogos_del.html'

    if not producto:
        return redirect('inv:producto_list')
    
    if request.method == 'GET':
        context = {'obj': marca}

    if request.method == 'POST':
        producto.estado = False
        producto.save()
        return redirect('inv:producto_list')

    return render(request, template_name, context)

inv/templates/inv/catalogos_del.html
{% extends "base/base.html" %}

{% block page_content %}
    <form method="POST" class="form-inline">
        {% csrf_token %}
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Eliminar {{obj.descripcion}}?</div>
                        <button type="submit" class="btn btn-danger"><i class="fas fa-question-circle"></i>Si, Eliminar</button>                    
                        <a href="{% url 'inv:categoria_list' %}" class="btn btn-danger"><span class="fa fa-undo"></span>Cancelar</a>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-question-circle fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}
{% block js_page %}
{% endblock %}

inv/templates/inv/categoria_form.html
{% extends "base/base.html" %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
            <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
            <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} categoria
                        </div> 
                        <div class="dropdown-divide"></div>
                        <div class="row">
                            <div class="col-10">
                                <div class="input-group">
                                    <input type="text" name="descripcion" maxlegth=100 class="form-control" required id="id_descripcion" placeholder="Descripción"
                                    value="{% if obj %} {{obj.descripcion}}{% endif %}"
                                    >
                                </div>
                            </div>          
                            <div class="col-2">
                                <div class="form-group">
                                    <label for="id_estado">Estado</label>
                                    <input type="checkbox" name="estado" class="form-control" id="estado" 
                                    {% if obj.estado %}checked{% endif %}
                                    >
                                </div>
                            </div>
                            {% comment %} {{form.as_p}}      {% endcomment %}
                        </div>
                    </div>       
                </div>
                <div class="dropdown-divide"></div>   
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-primary"><span class="fa fa-save"></span>Guardar</button>
                        <a href="{% url 'inv:categoria_list' %}" class="btn btn-danger"><span class="fa fa-undo"></span>Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock %}

inv/templates/inv/categoria_list.html
{% extends "base/base.html" %}


{% block page_content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de categorías</h6>
            <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="fa fa-calendar-plus"></i>Nueva</a>                
            </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
               <div class="alert alert-info"> No hay categorías.</div>
            {% else %}  
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>                            
                            <th>Id</th>
                            <th>Descripción</th>
                            <th>Estado</th>
                            <th>F. creado</th>
                            <th>F. modificado</th>
                            <th class="all">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in obj %}
                            <tr>                                
                                <td>{{item.id}}</td>
                                <td>{{item.descripcion}}</td>
                                <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                                <td>{{item.fc|date:"d/m/Y H:i:s"}}</td>
                                <td>{{item.fm|date:"d/m/Y H:i:s"}}</td>
                                <td>                                
                                    <a href="{% url 'inv:categoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                    <a href="{% url 'inv:categoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>                    
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}     
        </div>
    </div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready(function(){
        $('.table').DataTable();
    })
</script>
{% endblock %}

inv/templates/inv/producto_list.html
{% extends "base/base.html" %}


{% block page_content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de unidades de medida</h6>
            <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" href="{% url 'inv:unidadmedida_new' %}"><i class="fa fa-calendar-plus"></i>Nueva</a>                
            </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
               <div class="alert alert-info"> No hay unidades de medida.</div>
            {% else %}  
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>                            
                            <th>Id</th>
                            <th>Descripción</th>
                            <th>Estado</th>
                            <th>F. creado</th>
                            <th>F. modificado</th>
                            <th class="all">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in obj %}
                            <tr>                                
                                <td>{{item.id}}</td>
                                <td>{{item.descripcion}}</td>
                                <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                                <td>{{item.fc|date:"d/m/Y H:i:s"}}</td>
                                <td>{{item.fm|date:"d/m/Y H:i:s"}}</td>
                                <td>                                
                                    <a href="{% url 'inv:unidadmedida_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                    <a href="{% url 'inv:unidadmedida_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>                    
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}     
        </div>
    </div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready(function(){
        $('.table').DataTable();
    })
</script>
{% endblock %}

inv/templates/inv/subcategoria_list.html
{% extends "base/base.html" %}


{% block page_content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de subcategorías</h6>
            <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" href="{% url 'inv:subcategoria_new' %}"><i class="fa fa-calendar-plus"></i>Nueva</a>                
            </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
               <div class="alert alert-info"> No hay subcategorías.</div>
            {% else %}  
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Descripción</th>
                            <th>Estado</th>
                            <th>F. creado</th>
                            <th>F. modificado</th>
                            <th class="all">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in obj %}
                            <tr>
                                <td>{{item.id}}</td>
                                <td>{{item.descripcion}}</td>
                                <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                                <td>{{item.fc|date:"d/m/Y H:i:s"}}</td>
                                <td>{{item.fm|date:"d/m/Y H:i:s"}}</td>
                                <td>                                
                                    <a href="{% url 'inv:subcategoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                    <a href="{% url 'inv:subcategoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>                    
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}     
        </div>
    </div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready(function(){
        $('.table').DataTable();
    })
</script>
{% endblock %}

inv/templates/inv/unidadmedida_list.html
{% extends "base/base.html" %}


{% block page_content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de unidades de medida</h6>
            <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" href="{% url 'inv:unidadmedida_new' %}"><i class="fa fa-calendar-plus"></i>Nueva</a>                
            </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
               <div class="alert alert-info"> No hay unidades de medida.</div>
            {% else %}  
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>                            
                            <th>Id</th>
                            <th>Descripción</th>
                            <th>Estado</th>
                            <th>F. creado</th>
                            <th>F. modificado</th>
                            <th class="all">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in obj %}
                            <tr>                                
                                <td>{{item.id}}</td>
                                <td>{{item.descripcion}}</td>
                                <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                                <td>{{item.fc|date:"d/m/Y H:i:s"}}</td>
                                <td>{{item.fm|date:"d/m/Y H:i:s"}}</td>
                                <td>                                
                                    <a href="{% url 'inv:unidadmedida_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                    <a href="{% url 'inv:unidadmedida_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>                    
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}     
        </div>
    </div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready(function(){
        $('.table').DataTable();
    })
</script>
{% endblock %}