app_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('base.urls', 'base'), namespace="base")),
    path('inv/', include(('inv.urls', 'inv'), namespace="inv")),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace="cmp")),
    path('admin/', admin.site.urls),
]

cmp/urls.py
from django.urls import path
from cmp.views import (
    ProveedorView, ProveedorNew, ProveedorEdit, proveedor_inactivar
)

urlpatterns = [
    path('proveedor/', ProveedorView.as_view(), name="proveedor_list"),
    path('proveedor/new/', ProveedorNew.as_view(), name="proveedor_new"),
    path('proveedor/edit/<int:pk>', ProveedorEdit.as_view(), name="proveedor_edit"),

    path('proveedor/inactivar/<int:id>', proveedor_inactivar, name="proveedor_inactivar")
    
]

cmp/models.py
from django.db import models
from base.models import ModelBase

# Create your models here.
class Proveedor(ModelBase):
    descripcion = models.CharField(max_length=100, unique=True)
    direccion = models.CharField(max_length=250, null=True, blank=True)
    contacto = models.CharField(max_length=100)
    telefono = models.CharField(max_length=10, null=True, blank=True)
    correo = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super().save()

    class Meta:
        verbose_name_plural = 'Proveedores'  

cmp/forms.py
from django import forms

from .models import Proveedor


class ProveedorForm(forms.ModelForm):
    correo = forms.EmailField(max_length=254)
    class Meta:
        model = Proveedor
        exclude = [
            'um', 'fm', 'uc', 'fc'
        ]
        widget = {
            'descripcion': forms.TextInput()
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })   

cmp/views.py
import json

from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponse
 
from .models import Proveedor
from .forms import ProveedorForm

# Create your views here.
class ProveedorView(LoginRequiredMixin, generic.ListView):
    model = Proveedor
    template_name = 'cmp/proveedor_list.html'
    context_object_name = 'obj'
    login_url = 'base:login'

class ProveedorNew(LoginRequiredMixin, generic.CreateView):
    model = Proveedor
    template_name = 'cmp/proveedor_form.html'
    context_object_name = 'obj'
    form_class = ProveedorForm
    success_url = reverse_lazy('cmp:proveedor_list')
    login_url = 'base:login'

    def form_valid(self, form):
        form.instance.uc = self.request.user        
        return super().form_valid(form)

class ProveedorEdit(LoginRequiredMixin, generic.UpdateView):
    model = Proveedor
    template_name = 'cmp/proveedor_form.html'
    context_object_name = 'obj'
    form_class = ProveedorForm
    success_url = reverse_lazy('cmp:proveedor_list')
    login_url = 'base:login'

    def form_valid(self, form):
        form.instance.um = self.request.user.id       
        return super().form_valid(form)

def proveedor_inactivar(request, id):
    template_name = 'cmp/inactivar_prv.html'
    context = {}
    prv = Proveedor.objects.filter(pk=id).first()

    if not prv:
        return HttpResponse('Proveedor no existe {}'.format(id))

    if request.method == 'GET':
        context = {'obj': prv}

    if request.method == 'POST':
        prv.estado = False
        prv.save()
        context = {'obj': 'ok'}
        return HttpResponse('Proveedor inactivado')

    return render(request, template_name, context)

cmp/templates/cmp/inactivar_prv.html
<div class="modal-dialog">
    <div class="modal-content">
        <form method="POST" class="form-inline">
            {% csrf_token %}
            <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿inactivar <b>{{obj.descripcion}}</b>?</div>
                            <button type="button" class="btn btn-danger" id ="btn_inactivar"><i class="fas fa-question-circle"></i>Si, Eliminar</button>                    
                            <button type="button" onclick="return cerrar_modal()" class="btn btn-success"><span class="fa fa-undo">Cancelar</button>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-question-circle fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
$(document).ready(function(){
    var token = $('input[name=csrfmiddlewaretoken]').val();

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                xhr.setRequestHeader("X-CSRFToken", token);
            }
        }
    });

    $('#btn_inactivar').click(function(e){
        e.preventDefault();        

        var id = "{{ obj.id }}";
        var template = "{% url 'cmp:proveedor_inactivar' obj.id %}";            
        var data = {"id": id };
        data = JSON.stringify(data)

        $.ajax({
            type: 'POST',
            url: template,
            data: data,
            beforeSend: function(xhr,settings){
                $.ajaxSettings.beforeSend(xhr, settings);
            },            
            success: function(response){                
                cerrar_modal();                
                var tipo = (response.startsWith('Proveedor no existe') ? 'red':'green');
                console.log(tipo);
                mensaje(response, tipo);
            },
            error: function(jqXHR, textStatus, errorThrow){                
                cerrar_modal();
                mensaje(errorThrow, "red")
            }
        })
    })
})
</script>

cmp/templates/cmp/proveedor_form.html
<div class="modal-dialog">
    <div class="modal-content">
        <form method="POST" role="form" class="form-inline" action="{% if obj %}{% url 'cmp:proveedor_edit' obj.id %}{% else %}{% url 'cmp:proveedor_new' %}{% endif %}">
            {% csrf_token %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                    <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                    <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                    {% if obj %} Editar {% else %} Nuevo {% endif %} Proveedor
                                </div> 
                                <div class="dropdown-divide"></div>
                                <div class="row">                                     
                                    {{ form.as_p }}                                             
                                </div>
                            </div>       
                        </div>
                        <div class="dropdown-divide"></div>   
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-primary"><span class="fa fa-save"></span>Guardar</button>                                
                                <button type="button" onclick="return cerrar_modal()" class="btn btn-success"><span class="fa fa-undo">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

cmp/templates/cmp/proveedor_list.html
{% extends "base/base.html" %}


{% block page_content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de proveedor</h6>
            <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" onclick="return abrir_modal('{% url 'cmp:proveedor_new' %}')" href="#"><i class="fa fa-calendar-plus"></i>Nueva</a>                
            </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
               <div class="alert alert-info"> No hay proveedores.</div>
            {% else %}  
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>                            
                            <th>Descripcion</th>
                            <th>Direccion</th>
                            <th>Contacto</th>                            
                            <th>Telefono</th>
                            <th>Correo</th>
                            <th class="all">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in obj %}
                            <tr>                                
                                <td>{{ item.descripcion }}</td>
                                <td>{{ item.direccion }}</td>
                                <td>{{ item.contacto }}</td>
                                <td>{{ item.telefono }}</td>
                                <td>{{ item.correo }}</td>
                                <td>                                
                                    <button onclick="return abrir_modal('{% url 'cmp:proveedor_edit' item.id %}')" href="#" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></button>
                                    <button onclick="return abrir_modal('{% url 'cmp:proveedor_inactivar' item.id %}')" href="#" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></button>
                                    
                                    {% comment %} <a href="{% url 'inv:proveedor_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a> {% endcomment %}
                                </td>
                            </tr>                    
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}     
        </div>
    </div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready(function(){
        $('.table').DataTable();
    })
</script>
{% endblock %}