app_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('base.urls', 'base'), namespace="base")),
    path('inv/', include(('inv.urls', 'inv'), namespace="inv")),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace="cmp")),
    path('admin/', admin.site.urls),
]

base/urls.py
from django.urls import path
from base.views import Home, HomeSinPrivilegios
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('login/', auth_views.LoginView.as_view(template_name='base/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='base/login.html'), name="logout"),  
    path('sinprivilegios/', HomeSinPrivilegios.as_view(), name="sinprivilegios")    
]

cmp/urls.py
from django.urls import path
from cmp.views import (
    ProveedorView, ProveedorNew, ProveedorEdit, proveedor_inactivar
)

urlpatterns = [
    path('proveedor/', ProveedorView.as_view(), name="proveedor_list"),
    path('proveedor/new/', ProveedorNew.as_view(), name="proveedor_new"),
    path('proveedor/edit/<int:pk>', ProveedorEdit.as_view(), name="proveedor_edit"),

    path('proveedor/inactivar/<int:id>', proveedor_inactivar, name="proveedor_inactivar")
    
]

base/models.py
from django.db import models
from django.contrib.auth.models import User


class ModelBase(models.Model):
    '''
    auto_now_add = agrega fecha y hora solo en creacion
    auto_now = cada vez que cambie algo cambia la fecha
    '''
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True, null=True)

    class Meta:
        ''' No toma encuenta el modelo al crear migraciones'''
        abstract = True

base/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import AnonymousUser
from django.views import generic
# Create your views here.

class SinPrivilegios(LoginRequiredMixin, PermissionRequiredMixin):
    raise_exception=False
    redirect_field_name='redirect_to'
    login_url = 'base:login'
    context_object_name = 'obj'

    def handle_no_permission(self):
        if  not self.request.user== AnonymousUser():
            self.login_url = 'base:sinprivilegios'
        return HttpResponseRedirect(reverse_lazy(self.login_url))


class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'base/home.html'
    login_url = '/login'

class HomeSinPrivilegios(generic.TemplateView):
    template_name = 'base/sin_privilegios.html'

base/templates/base/home.html
{% extends 'base/base.html' %}

{% block page_content %}
hola
{% endblock %}

base/templates/base/login.html
{% extends "base/base.html" %}

<!-- Outer Row -->
{% block side_bar %}{% endblock %}
{% block top_bar %}{% endblock %}
{% block page_content %}
<div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
            <div class="col-lg-6">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                        <small class="text-danger">                            
                        </small>
                    </div>
                    <form class="user" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control form-control-user" id="id_username" name="username" aria-describedby="emailHelp" placeholder="Usuario">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control form-control-user" id="id_password" name="password" placeholder="Contraseña">
                        </div>
                        <div class="form-group">
                            <div class="custom-control custom-checkbox small">
                            <input type="checkbox" class="custom-control-input" id="customCheck">
                            <label class="custom-control-label" for="customCheck">Remember Me</label>
                            </div>
                        </div>
                        {# {form.as_p} #}
                        <button class="btn btn-primary btn-user btn-block" type="submit">Ingresar</button>                
                    </form>
                </div>
            </div>
        </div>
        </div>
    </div>

    </div>

</div>
{% endblock %}

{% block footer %}{% endblock %}


{% block js_page %}  
<script>
    {% if form.errors %}
        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}                    
                    mensaje("{{ error|escape }}", "red");
                {% endfor %}
            {% endif %}
        {% endfor %}

        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                mensaje(" {{ error|escape }}", "red");               
            {% endfor %}
        {% endif %}
    {% endif %}
</script>
{% endblock  %}

base/templates/base/sin_privilegios.html
{% extends 'base/base.html' %}
{% block page_content %}
    <div class="col-xl-6 col-md-6 mb-6">
        <div class="card border-left-danger shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                    Usuario: <mark>{{ user.username }}  {{user.get_full_name }}</mark> 
                </div>
                <div class="dropdown-divider"></div>

                <div class="row">
                    <mark>No tiene suficientes privilegios</mark> para cargar opción solicitada.
                    <br>
                    <small>Para poder acceder, debes loguearte con un usuario con privilegios necesarios.</small>

                </div>
                <div class="dropdown-divider"></div>
                <div class="row">
                    <div class="col">
                        <a href="{% url 'base:home' %}" class="btn btn-success"><span class="fa fa-home"></span> Ir a Inicio</a>
                        <a href="{% url 'base:login' %}" class="btn btn-success"><span class="fa fa-user"></span> Ingresar con otro Usuario</a>
                    </div>
                </div>
            </div>
            <div class="col-auto">
                <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
            </div>
            </div>
        </div>
        </div>
    </div>
{% endblock %}